[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "vis_nav"
version = "1.0.0"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["vis_nav*"]
